"""Archer v7 review layout from the supplied 2026-10-02 template (headers only)."""

V7_COLUMNS = (
    'Sample',
    'Classification',
    'Report',
    'Artifact',
    'Symbol',
    'HGVSp',
    'HGVSc',
    'Depth',
    'AO',
    'AF',
    'Quality Score',
    'AF Outlier P Value',
    'Intra Job AF Outlier P Value',
    'TO',
    'Rept',
    'Tier I',
    'Tier II',
    'Tier III',
    'Tier IV',
    'Germ',
    'Artf',
    'gnomAD AF',
    'ClinVar Significance',
    'COSMICID',
    'MutationalStatus',
    'SIFT',
    'PolyPhen',
    'Genomic Location',
    'Ref/Alt Allele',
    'Exon',
    'Consequence',
    'Source',
    'HRUN',
    'DAO',
    'DDP',
    'DAF',
    'UAO',
    'Has Seq Dir Bias',
    'Seq Dir Bias Ratio',
    'SDB pVal',
    'Has Sample Strand Bias',
    'Sample Strand Bias Ratio',
    'SSB pVal',
    'Trans',
    'Canonical',
    'Codons',
    'Type',
    'DBSNPID',
    'Variant disease name',
    'FunctionalStatus',
    'Variant Call',
    'DRE',
    'DRO',
    'FATHMM',
    'FEDSP',
    'FEDSR',
    'Intra Job AFC',
    'Intra Job AOC',
    'Intra Job BN',
    'Intra Job MDAF',
    'Intra Job DAF Outlier P Value',
    'Intra Job DAOC',
    'Intra Job DAFC',
    'Intra Job DBN',
    'Intra Job DMDAF',
    'Intra Job D95MDAF',
    'Intra Job SAF Outlier P Value',
    'Intra Job SAOC',
    'Intra Job SAFC',
    'Intra Job SBN',
    'Intra Job SMDAF',
    'Intra Job S95MDAF',
    'MA Match',
    'Min Outlier P Value',
    'ND AF Outlier P Value',
    'ND AFC',
    'ND AOC',
    'ND BN',
    'ND MDAF',
    'ND 95MDAF',
    'ND DAF Outlier P Value',
    'ND DAFC',
    'ND DAOC',
    'ND DBN',
    'ND DMDAF',
    'ND D95MDAF',
    'ND SAF Outlier P Value',
    'ND SAOC',
    'ND SAFC',
    'ND SBN',
    'ND SMDAF',
    'ND S95MDAF',
    'Primer Alt Reads +',
    'Primer Alt Reads -',
    'Primer Ref Reads +',
    'Primer Ref Reads -',
    'RO',
    'Seq Alt Reads +',
    'Seq Alt Reads -',
    'Seq Ref Reads +',
    'Seq Ref Reads -',
    'SRE',
    'UDP',
    'URO',
    'Variant Name',
    'UAF',
    '95MDAF',
    'Intra Job 95MDAF',
)

V7_HIDDEN_COLUMNS = frozenset({
    'Report',
    'Artifact',
    'Has Seq Dir Bias',
    'Has Sample Strand Bias',
    'FunctionalStatus',
    'Variant Call',
    'DRE',
    'DRO',
    'FATHMM',
    'FEDSP',
    'FEDSR',
    'Intra Job AFC',
    'Intra Job AOC',
    'Intra Job BN',
    'Intra Job MDAF',
    'Intra Job DAF Outlier P Value',
    'Intra Job DAOC',
    'Intra Job DAFC',
    'Intra Job DBN',
    'Intra Job DMDAF',
    'Intra Job D95MDAF',
    'Intra Job SAF Outlier P Value',
    'Intra Job SAOC',
    'Intra Job SAFC',
    'Intra Job SBN',
    'Intra Job SMDAF',
    'Intra Job S95MDAF',
    'MA Match',
    'Min Outlier P Value',
    'ND AF Outlier P Value',
    'ND AFC',
    'ND AOC',
    'ND BN',
    'ND MDAF',
    'ND 95MDAF',
    'ND DAF Outlier P Value',
    'ND DAFC',
    'ND DAOC',
    'ND DBN',
    'ND DMDAF',
    'ND D95MDAF',
    'ND SAF Outlier P Value',
    'ND SAOC',
    'ND SAFC',
    'ND SBN',
    'ND SMDAF',
    'ND S95MDAF',
    'Primer Alt Reads +',
    'Primer Alt Reads -',
    'Primer Ref Reads +',
    'Primer Ref Reads -',
    'RO',
    'Seq Alt Reads +',
    'Seq Alt Reads -',
    'Seq Ref Reads +',
    'Seq Ref Reads -',
    'SRE',
    'UDP',
    'URO',
    'Variant Name',
})
